<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatDongSanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bat_dong_sans')->insert([
            [
                'tieu_de' => 'Căn hộ cao cấp Quận 1',
                'mo_ta' => 'Căn hộ view sông, nội thất đầy đủ, an ninh 24/7.',
                'gia' => 5000000000,
                'dien_tich' => 100,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'tinh_id' => 1,
                'quan_id' => 1,
                'dia_chi_id' => 1,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà phố mặt tiền Quận 7',
                'mo_ta' => 'Nhà phố 3 tầng, vị trí vàng, gần trung tâm.',
                'gia' => 8000000000,
                'dien_tich' => 150,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'tinh_id' => 1,
                'quan_id' => 4,
                'dia_chi_id' => 2,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất nền Bình Dương sổ đỏ',
                'mo_ta' => 'Đất nền sổ đỏ, gần khu công nghiệp, tiện kinh doanh.',
                'gia' => 2000000000,
                'dien_tich' => 200,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 3,
                'tinh_id' => 4,
                'quan_id' => 8,
                'dia_chi_id' => 4,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư cao cấp Bình Thạnh',
                'mo_ta' => 'Chung cư tiện ích đầy đủ, an ninh 24/7, gần metro.',
                'gia' => 3000000000,
                'dien_tich' => 80,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'tinh_id' => 1,
                'quan_id' => 5,
                'dia_chi_id' => 3,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa biển Andromeda Quận 2',
                'mo_ta' => 'Villa 5 sao, hồ bơi, sân vườn rộng, view biển tuyệt đẹp.',
                'gia' => 15000000000,
                'dien_tich' => 300,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'tinh_id' => 1,
                'quan_id' => 2,
                'dia_chi_id' => 6,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Vườn biệt thự Thuận An - Bình Dương',
                'mo_ta' => 'Dự án vườn biệt thự cây xanh, không khí sạch.',
                'gia' => 4500000000,
                'dien_tich' => 180,
                'loai_id' => 3,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 2,
                'tinh_id' => 4,
                'quan_id' => 9,
                'dia_chi_id' => 5,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kho xưởng cho thuê Tân Bình',
                'mo_ta' => 'Kho xưởng hiện đại, tiện cho logistics và manufacturing.',
                'gia' => 1500000000,
                'dien_tich' => 500,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 3,
                'tinh_id' => 1,
                'quan_id' => 6,
                'dia_chi_id' => 1,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
