<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChucNangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('chuc_nangs')->delete();
        DB::table('chuc_nangs')->truncate();
        DB::table('chuc_nangs')->insert([
            [
                'id' => 1,
                'ten_chuc_nang' => 'Xem danh sách bất động sản',
                'url_chuc_nang' => '/api/admin/bds',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem danh sách tất cả các bất động sản đã được đăng trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'ten_chuc_nang' => 'Tạo tin bất động sản',
                'url_chuc_nang' => '/api/admin/bds',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin tạo mới một tin bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'ten_chuc_nang' => 'Chỉnh sửa tin bất động sản',
                'url_chuc_nang' => '/api/admin/bds',
                'methods_chuc_nang' => 'PUT',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin chỉnh sửa thông tin của một tin bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'ten_chuc_nang' => 'Xóa tin bất động sản',
                'url_chuc_nang' => '/api/admin/bds',
                'methods_chuc_nang' => 'DELETE',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xóa một tin bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'ten_chuc_nang' => 'Duyệt tin bất động sản',
                'url_chuc_nang' => '/api/admin/bds',
                'methods_chuc_nang' => 'PATCH',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin duyệt một tin bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'ten_chuc_nang' => 'Quản lý gói tin',
                'url_chuc_nang' => '/api/admin/goi-tin',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin quản lý các gói tin đăng ký trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'ten_chuc_nang' => 'Quản lý giao dịch',
                'url_chuc_nang' => '/api/admin/giao-dich',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin quản lý các giao dịch trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'ten_chuc_nang' => 'Quản lý người dùng',
                'url_chuc_nang' => '/api/admin/nguoi-dung',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin quản lý các người dùng trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'ten_chuc_nang' => 'Quản lý admin',
                'url_chuc_nang' => '/api/admin/admin',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin quản lý các tài khoản admin trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'ten_chuc_nang' => 'Xem báo cáo',
                'url_chuc_nang' => '/api/admin/thong-ke',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem báo cáo thống kê trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== ADMIN - KHÁCH HÀNG ====================
            [
                'id' => 11,
                'ten_chuc_nang' => 'Xem danh sách khách hàng',
                'url_chuc_nang' => '/api/admin/khach-hang/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem danh sách all khách hàng trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'ten_chuc_nang' => 'Tìm kiếm khách hàng',
                'url_chuc_nang' => '/api/admin/khach-hang/search',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin tìm kiếm khách hàng theo tên hoặc email.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'ten_chuc_nang' => 'Cập nhật KHÁCH HÀNG',
                'url_chuc_nang' => '/api/admin/khach-hang/update',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin cập nhật thông tin khách hàng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'ten_chuc_nang' => 'Xóa khách hàng',
                'url_chuc_nang' => '/api/admin/khach-hang/delete',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xóa tài khoản khách hàng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== ADMIN - MÔI GIỚI ====================
            [
                'id' => 15,
                'ten_chuc_nang' => 'Xem danh sách môi giới',
                'url_chuc_nang' => '/api/admin/moi-gioi/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem danh sách all môi giới trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'ten_chuc_nang' => 'Tìm kiếm môi giới',
                'url_chuc_nang' => '/api/admin/moi-gioi/search',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin tìm kiếm môi giới theo tên hoặc email.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'ten_chuc_nang' => 'Cập nhật môi giới',
                'url_chuc_nang' => '/api/admin/moi-gioi/update',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin cập nhật thông tin môi giới.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'ten_chuc_nang' => 'Xóa môi giới',
                'url_chuc_nang' => '/api/admin/moi-gioi/delete',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xóa tài khoản môi giới.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== ADMIN - GÓI TIN ====================
            [
                'id' => 19,
                'ten_chuc_nang' => 'Danh sách gói tin',
                'url_chuc_nang' => '/api/admin/goi-tin/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem danh sách all gói tin quảng cáo.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'ten_chuc_nang' => 'Tạo gói tin',
                'url_chuc_nang' => '/api/admin/goi-tin/create',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin tạo mới gói tin quảng cáo.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'ten_chuc_nang' => 'Cập nhật gói tin',
                'url_chuc_nang' => '/api/admin/goi-tin/update',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin cập nhật thông tin gói tin.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'ten_chuc_nang' => 'Xóa gói tin',
                'url_chuc_nang' => '/api/admin/goi-tin/delete',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xóa gói tin quảng cáo.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== ADMIN - PROFILE ====================
            [
                'id' => 23,
                'ten_chuc_nang' => 'Xem profile admin',
                'url_chuc_nang' => '/api/admin/profile',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem thông tin profile của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'ten_chuc_nang' => 'Cập nhật profile admin',
                'url_chuc_nang' => '/api/admin/update-profile',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin cập nhật thông tin profile của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'ten_chuc_nang' => 'Logout admin từ all devices',
                'url_chuc_nang' => '/api/admin/dang-xuat-tat-ca',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin đăng xuất từ tất cả các thiết bị.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== ADMIN - THỐNG KÊ ====================
            [
                'id' => 26,
                'ten_chuc_nang' => 'Thống kê doanh thu',
                'url_chuc_nang' => '/api/admin/doanh-thu',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem thống kê doanh thu theo khoảng thời gian.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'ten_chuc_nang' => 'Thống kê người dùng',
                'url_chuc_nang' => '/api/admin/user',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem thống kê người dùng theo khoảng thời gian.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'ten_chuc_nang' => 'Xem danh sách giao dịch',
                'url_chuc_nang' => '/api/admin/giao-dich/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xem danh sách tất cả giao dịch trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== PUBLIC - BẤT ĐỘNG SẢN ====================
            [
                'id' => 29,
                'ten_chuc_nang' => 'Xem danh sách BDS public',
                'url_chuc_nang' => '/api/bds',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép user xem danh sách bất động sản (công khai).',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'ten_chuc_nang' => 'Tìm kiếm BDS',
                'url_chuc_nang' => '/api/bds/tim-kiem',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép user tìm kiếm bất động sản theo tiêu chí.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'ten_chuc_nang' => 'Chi tiết BDS',
                'url_chuc_nang' => '/api/bds/{id}',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép user xem chi tiết thông tin của một bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'ten_chuc_nang' => 'Xem thông tin môi giới',
                'url_chuc_nang' => '/api/bds/{id}/moi-gioi',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép user xem thông tin môi giới của bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'ten_chuc_nang' => 'Xem bản đồ BDS',
                'url_chuc_nang' => '/api/bds/map-data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép user xem bất động sản trên bản đồ theo khu vực.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== MÔI GIỚI - PROFILE ====================
            [
                'id' => 34,
                'ten_chuc_nang' => 'Xem profile môi giới',
                'url_chuc_nang' => '/api/moi-gioi/profile',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới xem thông tin profile của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'ten_chuc_nang' => 'Cập nhật profile môi giới',
                'url_chuc_nang' => '/api/moi-gioi/update-profile',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới cập nhật thông tin profile của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== MÔI GIỚI - BẤT ĐỘNG SẢN ====================
            [
                'id' => 36,
                'ten_chuc_nang' => 'Xem danh sách BDS của tôi',
                'url_chuc_nang' => '/api/moi-gioi/bds/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới xem danh sách bất động sản của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'ten_chuc_nang' => 'Đăng BDS mới',
                'url_chuc_nang' => '/api/moi-gioi/bds/create',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới đăng tin bất động sản mới.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'ten_chuc_nang' => 'Cập nhật BDS',
                'url_chuc_nang' => '/api/moi-gioi/bds/update',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới cập nhật thông tin bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'ten_chuc_nang' => 'Xóa BDS',
                'url_chuc_nang' => '/api/moi-gioi/bds/delete',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới xóa tin bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== MÔI GIỚI - GÓI TIN ====================
            [
                'id' => 40,
                'ten_chuc_nang' => 'Xem danh sách gói tin',
                'url_chuc_nang' => '/api/moi-gioi/goi-tin/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới xem danh sách gói tin quảng cáo.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'ten_chuc_nang' => 'Mua gói tin',
                'url_chuc_nang' => '/api/moi-gioi/goi-tin/mua',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới mua gói tin để tăng số lượng tin và thời hạn đăng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== MÔI GIỚI - THÔNG BÁO ====================
            [
                'id' => 42,
                'ten_chuc_nang' => 'Xem thông báo',
                'url_chuc_nang' => '/api/moi-gioi/thong-bao',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới xem thông báo khi khách thả tim BDS.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== MÔI GIỚI - GIAO DỊCH ====================
            [
                'id' => 43,
                'ten_chuc_nang' => 'Xem lịch sử giao dịch',
                'url_chuc_nang' => '/api/moi-gioi/giao-dich/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép môi giới xem lịch sử các giao dịch của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== KHÁCH HÀNG - PROFILE ====================
            [
                'id' => 44,
                'ten_chuc_nang' => 'Xem profile khách hàng',
                'url_chuc_nang' => '/api/khach-hang/profile',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép khách hàng xem thông tin profile của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 45,
                'ten_chuc_nang' => 'Cập nhật profile khách hàng',
                'url_chuc_nang' => '/api/khach-hang/update-profile',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép khách hàng cập nhật thông tin profile của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== KHÁCH HÀNG - YÊU THÍCH ====================
            [
                'id' => 46,
                'ten_chuc_nang' => 'Thả tim BDS',
                'url_chuc_nang' => '/api/khach-hang/bds/yeu-thich',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép khách hàng thả tim yêu thích bất động sản.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 47,
                'ten_chuc_nang' => 'Xem danh sách BDS yêu thích',
                'url_chuc_nang' => '/api/khach-hang/bds/yeu-thich/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép khách hàng xem danh sách bất động sản yêu thích của chính mình.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== KHÁCH HÀNG - MUA GÓI ====================
            [
                'id' => 48, 
                'ten_chuc_nang' => 'Mua gói -> Trở thành môi giới',
                'url_chuc_nang' => '/api/khach-hang/mua-goi',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép khách hàng mua gói tin để trở thành môi giới.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // ==================== AI & CHATBOT ====================
            [
                'id' => 49,
                'ten_chuc_nang' => 'Dự đoán giá BDS',
                'url_chuc_nang' => '/api/ai/dinh-gia',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng sử dụng AI để dự đoán giá bất động sản dựa trên tiêu chí.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 50,
                'ten_chuc_nang' => 'Chat với chatbot',
                'url_chuc_nang' => '/api/chatbot',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép user chat tương tác với chatbot hỗ trợ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [   'id' => 51, //ChucVuCrl
                'ten_chuc_nang' => 'Thêm Mới Chức Vụ',
                'url_chuc_nang' => '/api/admin/chuc-vu/create',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin thêm mới một chức vụ với tên chức vụ và slug chức vụ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [   
                'id' => 52, //ChucVuCrl
                'ten_chuc_nang' => 'Lấy dữ liệu chức vụ',
                'url_chuc_nang' => '/api/admin/chuc-vu/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin lấy dữ liệu tất cả chức vụ trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 53, //ChucVuCrl
                'ten_chuc_nang' => 'Cập Nhật Chức Vụ',
                'url_chuc_nang' => '/api/admin/chuc-vu/update',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin cập nhật trạng thái của một chức vụ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 54, //ChucVuCrl
                'ten_chuc_nang' => 'Xóa Chức Vụ',
                'url_chuc_nang' => '/api/admin/chuc-vu/delete',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin xóa một chức vụ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 55, //ChucVuCrl
                'ten_chuc_nang' => 'Cấp chức năng cho Chức Vụ',
                'url_chuc_nang' => '/api/admin/phan-quyen/chuc-vu/create',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin cấp chức năng cho một chức vụ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 56, //PhanQuyenCrl
                'ten_chuc_nang' => 'Hủy chức năng của Chức Vụ ',
                'url_chuc_nang' => '/api/admin/phan-quyen/chuc-vu/delete',
                'methods_chuc_nang' => 'POST',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin hủy chức năng của một chức vụ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 57, //ChucNangCrl
                'ten_chuc_nang' => 'Lấy dữ liệu chức năng',
                'url_chuc_nang' => '/api/admin/chuc-nang/data',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin lấy dữ liệu tất cả chức năng trên hệ thống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 58, //PhanQuyenCrl
                'ten_chuc_nang' => 'Lấy dữ liệu chi tiết chức năng',
                'url_chuc_nang' => '/api/admin/phan-quyen/data/{id_chuc_vu}',
                'methods_chuc_nang' => 'GET',
                'mo_ta_chuc_nang' => 'Chức năng cho phép admin lấy dữ liệu chi tiết của một chức năng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
